import java.io.IOException;
import java.math.BigDecimal;
import java.util.concurrent.ExecutionException;

import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.core.methods.response.Web3ClientVersion;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.Transfer;
import org.web3j.utils.Convert;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public boolean transfer(String toAddress) {
		Web3j web3 = Web3j.build(new HttpService()); // defaults to http://localhost:8545/
		Web3ClientVersion web3ClientVersion;
		try {
			web3ClientVersion = web3.web3ClientVersion().send();
		} catch (IOException e) {
			throw (new RuntimeException(e));
		}
		String clientVersion = web3ClientVersion.getWeb3ClientVersion();
		System.out.println(clientVersion);

		try {
			System.out.println(web3.ethCoinbase().sendAsync().get().getAddress());
		} catch (InterruptedException | ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// send a transaction to a given address
		Credentials credentials;

		try {
			credentials = WalletUtils.loadCredentials("12341234",
					"/Users/binod/ethereum/localnetwork/keystore/UTC--2018-08-14T02-31-04.782982000Z--3980640925047be885b48ab4f63c53318059421d");
			TransactionReceipt transactionReceipt = Transfer
					.sendFunds(web3, credentials, toAddress, BigDecimal.valueOf(5.0), Convert.Unit.ETHER)
					.send();
			System.out.println(transactionReceipt.toString());
		} catch (Exception e) {
			throw (new RuntimeException(e));
		}

		return true;
	}
}
