import java.io.IOException;
import java.util.concurrent.ExecutionException;

import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.Web3ClientVersion;
import org.web3j.protocol.http.HttpService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public boolean createAccount(String accountName) {
		Web3j web3 = Web3j.build(new HttpService()); // defaults to http://localhost:8545/
		Web3ClientVersion web3ClientVersion;
		try {
			web3ClientVersion = web3.web3ClientVersion().send();
		} catch (IOException e) {
			throw (new RuntimeException(e));
		}
		String clientVersion = web3ClientVersion.getWeb3ClientVersion();
		System.out.println(clientVersion);

		try {
			System.out.println(web3.ethCoinbase().sendAsync().get().getAddress());
		} catch (InterruptedException | ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return true;
	}
}
