package com.power2peer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.BeforeClass;
import org.junit.Test;

import com.power2peer.BlockchainConfig;
import com.power2peer.EtherTransfer;

public class EtherTransferTest {
	private static BlockchainConfig config;

	@BeforeClass
	public static void setup() {
		String url = "https://Power2Peer.com/t/";
		String keystorefile = "/Users/binod/Downloads/UTC--2018-08-14T03-03-16.633994578Z--b19aeb8b89c25d5cd038dfcf071297113a520546";
		config = BlockchainConfig.newConfig(url, keystorefile, "12341234");
	}

	@Test
	public void testSomeLibraryMethod() {

		EtherTransfer classUnderTest = new EtherTransfer(config);
		assertTrue("someLibraryMethod should return 'true'",
				classUnderTest.transfer("0x3980640925047be885b48ab4f63c53318059421d"));
	}
}
